Stan is a probabilistic programming language for statistical inference written in C++.[1] The Stan language is used to specify a (Bayesian) statistical model with an imperative program calculating the log probability density function.[1] 
Stan is licensed under the New BSD License. Stan is named in honour of Stanislaw Ulam, pioneer of the Monte Carlo method.[1] 
Stan was created by Andrew Gelman and Bob Carpenter, with a development team consisting of 34 members[2]

### Interfaces[edit]
Stan can be accessed through several interfaces: 
CmdStan - command-line executable for the shell
RStan - integration with the R software environment, maintained by Andrew Gelman and colleagues
PyStan - integration with the Python programming language
MatlabStan - integration with the MATLAB numerical computing environment
Stan.jl - integration with the Julia programming language
StataStan - integration with Stata

### Algorithms[edit]
Stan implements gradient-based Markov chain Monte Carlo (MCMC) algorithms for Bayesian inference, stochastic, gradient-based variational Bayesian methods for approximate Bayesian inference, and gradient-based optimization for penalized maximum likelihood estimation. 
MCMC algorithms: 
No-U-Turn sampler[1][3] (NUTS), a variant of HMC and Stan's default MCMC engine
Hamiltonian Monte Carlo
Variational inference algorithms: 
Black-box Variational Inference[4]
Optimization algorithms: 
Limited-memory BFGS (Stan's default optimization algorithm)
Broyden–Fletcher–Goldfarb–Shanno algorithm
Laplace's method for classical standard error estimates and approximate Bayesian posteriors

### Automatic differentiation[edit]
Stan implements reverse-mode automatic differentiation to calculate gradients of the model, which is required by HMC, NUTS, L-BFGS, BFGS, and variational inference.[1] The automatic differentiation within Stan can be used outside of the probabilistic programming language. 

### Usage[edit]
Stan is used in fields including social science[5] and pharmaceutical statistics.[6] 
